/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import entidadesPOJO.Domicilio;
import entidadesPOJO.Nombre;

import entidadesPOJO.Cliente;
import entidadesPOJO.Cuenta;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.Month;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import persistencia.ClienteDTO;

/**
 *
 * @author elimo
 */
public class CapturarDatos extends javax.swing.JFrame {

    private int idNombre ;
    private int idDomicilio;
    private int idCliente;
    private int idCuenta;
    private Timer temporizador;

    /**
     * Creates new form CapturarDatos
     * @param frame
     */
    public CapturarDatos(JFrame frame) {
        initComponents();
        setLocationRelativeTo(frame);
        txtID.setText(String.valueOf(idCliente));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        txtNumExterior = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboBoxDia = new javax.swing.JComboBox<>();
        comboBoxMes = new javax.swing.JComboBox<>();
        comboBoxAño = new javax.swing.JComboBox<>();
        txtUsuario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnVerContraseña = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        txtConfirmarContraseña = new javax.swing.JPasswordField();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setText("Codigo Postal:");

        jLabel11.setText("Calle");

        jLabel12.setText("Número exterior:");

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAtras.setText("Volver atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel13.setText("Email:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Registrarte como cliente");

        jLabel3.setText("Apellido Paterno:");

        jLabel4.setText("Apellido Materno:");

        jLabel6.setText("Dia:");

        jLabel7.setText("Mes:");

        jLabel8.setText("Año:");

        comboBoxDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboBoxDiaMousePressed(evt);
            }
        });

        comboBoxMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboBoxMesMouseClicked(evt);
            }
        });

        comboBoxAño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboBoxAñoMouseClicked(evt);
            }
        });

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Usuario");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Contraseña");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Confirmar Contraseña:");

        btnVerContraseña.setText("Ver");
        btnVerContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVerContraseñaMousePressed(evt);
            }
        });
        btnVerContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerContraseñaActionPerformed(evt);
            }
        });

        txtContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtID.setEditable(false);

        jLabel5.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnAtras)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConfirmarContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtContraseña)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnVerContraseña)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCP, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                            .addComponent(comboBoxDia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(82, 82, 82)
                                                .addComponent(jLabel7))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(txtCalle, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxMes, javax.swing.GroupLayout.Alignment.LEADING, 0, 131, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNumExterior)
                                    .addComponent(comboBoxAño, 0, 141, Short.MAX_VALUE)
                                    .addComponent(txtApellidoMaterno))))))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(comboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumExterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(btnVerContraseña)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAtras)
                    .addComponent(txtConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        // Verificar si algún campo está vacío
if (txtCP.getText().isEmpty() || 
    txtCalle.getText().isEmpty() || 
    txtNumExterior.getText().isEmpty() || 
    txtEmail.getText().isEmpty() || 
    txtNombre.getText().isEmpty() || 
    txtApellidoPaterno.getText().isEmpty() || 
    txtApellidoMaterno.getText().isEmpty() || 
    txtUsuario.getText().isEmpty() || 
    txtContraseña.getPassword().length == 0 || 
    txtConfirmarContraseña.getPassword().length == 0) {
    // Al menos un campo está vacío
    JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
} else{
    ClienteDTO cliente = new ClienteDTO();
    try {
        cliente.guardarNombres(crearNombre());
        cliente.guardarDomicilio(crearDomicilio());
        cliente.guardarCliente(crearCliente(), idNombre, idDomicilio);
        cliente.guardarCuenta(crearCuenta(), idCliente);
         JOptionPane.showMessageDialog(this, "Bienvenido,¡te has ingresado con exito!", "Bienvenido"+" "+txtNombre.getText(), JOptionPane.PLAIN_MESSAGE);
    } catch (SQLException ex) {
        Logger.getLogger(CapturarDatos.class.getName()).log(Level.SEVERE, null, ex);
    }
    
}

if(!txtContraseña.getText().equals(txtConfirmarContraseña.getText()))

        JOptionPane.showMessageDialog(this, "La contraseña no coincide, porfavor verifique", "Contraseña no coincide", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_btnSiguienteActionPerformed

    private Nombre crearNombre() {
        idNombre++;

        Nombre nombre = new Nombre();
        String[] nombres = separarNombres();
        nombre.setPrimerNombre(nombres[0]);
        nombre.setSegundoNombre(nombres[1]);
        nombre.setApellidoPaterno(txtApellidoPaterno.getText());
        nombre.setApellidoMaterno(txtApellidoMaterno.getText());
        nombre.setIdNombre(idNombre);

        return nombre;

    }

    private Domicilio crearDomicilio() {
        
        idDomicilio++;

        Domicilio domicilio = new Domicilio();
        domicilio.setCalle(txtCalle.getText());
        domicilio.setCodigoPostal(Integer.parseInt(txtCP.getText()));
        domicilio.setIdDomicilio(idDomicilio);
        return domicilio;

    }

    private Cliente crearCliente() {

        idCliente++;
        Cliente cliente = new Cliente();
        cliente.setIdCliente(idCliente);
        cliente.setFechaNacimiento(comboBoxAño.getSelectedItem() + "-" + comboBoxDia.getSelectedItem() + "-" + obtenerDiasEnMes((String) comboBoxMes.getSelectedItem()));
        cliente.setIdDomicilio(idDomicilio);
        cliente.setIdNombre(idNombre);
        cliente.setEmail(txtEmail.getText());

        
        return cliente;

    }
    
    private int obtenerNumeroMes(String nombreMes) {
        // Convertir el nombre del mes a mayúsculas para que sea insensible a mayúsculas/minúsculas
        nombreMes = nombreMes.toUpperCase();
        
        // Obtener el número del mes usando el enum Month de Java 8
        switch (nombreMes) {
            case "ENERO":
                return Month.JANUARY.getValue();
            case "FEBRERO":
                return Month.FEBRUARY.getValue();
            case "MARZO":
                return Month.MARCH.getValue();
            case "ABRIL":
                return Month.APRIL.getValue();
            case "MAYO":
                return Month.MAY.getValue();
            case "JUNIO":
                return Month.JUNE.getValue();
            case "JULIO":
                return Month.JULY.getValue();
            case "AGOSTO":
                return Month.AUGUST.getValue();
            case "SEPTIEMBRE":
                return Month.SEPTEMBER.getValue();
            case "OCTUBRE":
                return Month.OCTOBER.getValue();
            case "NOVIEMBRE":
                return Month.NOVEMBER.getValue();
            case "DICIEMBRE":
                return Month.DECEMBER.getValue();
            default:
                // Si el nombre del mes no es válido, devolver -1 o lanzar una excepción según sea necesario
                return -1;
        }
    }

    private Cuenta crearCuenta() {
        LocalDate fechaActual = LocalDate.now();
        Cuenta cuenta = new Cuenta();
        cuenta.setUsuario(txtUsuario.getText());
        cuenta.setFechaApertura(String.valueOf(fechaActual));
        cuenta.setContraseña(txtContraseña.getText());
        cuenta.setIdCliente(idCliente);
        cuenta.setIdCuenta(idCuenta);
        cuenta.setSaldo(0);

        idCuenta++;
        return cuenta;

    }

    private String[] separarNombres() {
        String nombresTxt = txtNombre.getText();
        String[] nombres = nombresTxt.split(" ");

        return nombres;

    }
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        dispose();
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed


    private void comboBoxDiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboBoxDiaMousePressed
// Obtén una referencia al modelo de datos actual del JComboBox
        comboBoxDia.setEnabled(true);
        int diasMes = obtenerDiasEnMes(comboBoxMes.getSelectedItem().toString());
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
// Agrega los días del mes al modelo de datos
        for (int i = 1; i <= diasMes; i++) {
            modelo.addElement(String.valueOf(i));
        }
// Establece el modelo actualizado en el JComboBox
        comboBoxDia.setModel(modelo);


    }//GEN-LAST:event_comboBoxDiaMousePressed

    private void comboBoxMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboBoxMesMouseClicked
        // Crear JComboBox para los meses
        comboBoxDia.removeAllItems();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
            "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>(meses);

        comboBoxMes.setModel(modelo);


    }//GEN-LAST:event_comboBoxMesMouseClicked

    private void comboBoxAñoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboBoxAñoMouseClicked
        // TODO add your handling code here:
        Calendar calendario = Calendar.getInstance();
        int añoActual = calendario.get(Calendar.YEAR);
        int añoEdadMinima = añoActual - 18;
        int añoEdadMaxima = añoActual - 120;

        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();

        for (int i = añoEdadMinima; i >= añoEdadMaxima; i--) {
            modelo.addElement(String.valueOf(i));
        }

// Establece el modelo en el JComboBox
        comboBoxAño.setModel(modelo);

        if (comboBoxAño.getSelectedItem() == null || comboBoxMes.getSelectedItem() == null) {
            comboBoxDia.setEnabled(false);
        }


    }//GEN-LAST:event_comboBoxAñoMouseClicked

    private void btnVerContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerContraseñaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnVerContraseñaActionPerformed

    private void btnVerContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerContraseñaMousePressed
        // TODO add your handling code here:

        txtContraseña.setEchoChar((char) 0);
        btnVerContraseña.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                btnVerContraseña.setEnabled(false); // Deshabilitar el botón al hacer clic
                temporizador.start(); // Iniciar el temporizador para habilitar el botón después de un tiempo
            }
        });
        temporizador = new Timer(2000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                btnVerContraseña.setEnabled(true); // Habilitar el botón después de 3 segundos
                temporizador.stop();
                txtContraseña.setEchoChar('*');
                // Detener el temporizador después de habilitar el botón
            }
        });
    }//GEN-LAST:event_btnVerContraseñaMousePressed
    private int obtenerDiasEnMes(String mes) {
        GregorianCalendar calendario = new GregorianCalendar();
        int anioActual = Integer.parseInt(comboBoxAño.getSelectedItem().toString());

        switch (mes) {
            case "Febrero":
                return calendario.isLeapYear(anioActual) ? 29 : 28;
            case "Abril":
            case "Junio":
            case "Septiembre":
            case "Noviembre":
                return 30;
            default:
                return 31;
        }
    }

    // Función para obtener el número de días en un mes específico
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapturarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapturarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapturarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapturarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVerContraseña;
    private javax.swing.JComboBox<String> comboBoxAño;
    private javax.swing.JComboBox<String> comboBoxDia;
    private javax.swing.JComboBox<String> comboBoxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCP;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JPasswordField txtConfirmarContraseña;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumExterior;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
